### ISSUE TITLE
Works with VS2013

### ISSUE THREAD

**Issue by TomSmartBishop** [TomSmartBishop/image-comments#17]
<a href="https://github.com/clayu"><img src="https://avatars1.githubusercontent.com/u/4550734?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clayu](https://github.com/clayu)**
_Friday Jun 13, 2014 at 01:56 GMT_
_Originally opened as https://github.com/lukesdm/image-comments/pull/20_

----

Project works with VS2013. Not sure if it's still backward compatible. Output directory has working VS2013 vsix.

----

_**[clayu](https://github.com/clayu)** included the following code: https://github.com/lukesdm/image-comments/pull/20/commits_

**Comment by TomSmartBishop** [comment]
<a href="https://github.com/febitanya"><img src="https://avatars3.githubusercontent.com/u/7389743?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [febitanya](https://github.com/febitanya)**
_Wednesday Jun 18, 2014 at 05:11 GMT_

----

not working , do you do for working ?

**Comment by TomSmartBishop** [comment]
<a href="https://github.com/kairohmer"><img src="https://avatars2.githubusercontent.com/u/4760892?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kairohmer](https://github.com/kairohmer)**
_Wednesday Nov 05, 2014 at 10:09 GMT_

----

also tried to get it working for VS2013
- installed the visual studio 2013 SDK
- open the solution in VS2013
- upgraded both projects to .net4.5
- needed to update the reference for Microsoft.VisualStudio.Text.Logic
- added <SupportedProducts> element for VS2013 (just copied one of the others and changed to 12.0)

The projects build and you can install the .vsix (ImageCommentsPackage/bin/Release)
The extension seems to work, but I get an exception every time visual studio starts.

**Comment by TomSmartBishop** [comment]
<a href="https://github.com/febitanya"><img src="https://avatars3.githubusercontent.com/u/7389743?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [febitanya](https://github.com/febitanya)**
_Sunday Dec 21, 2014 at 18:44 GMT_

----

21-12-2014 8:43:43 PM - Searching for applicable products...
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio Premium 2013 
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio Professional 2013
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio Ultimate 2015 Preview
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio Premium 2015 Preview
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio Professional 2015 Preview
21-12-2014 8:43:43 PM - Found installed product - Microsoft Visual Studio 2015 Preview Shell (Integrated)
21-12-2014 8:43:43 PM - Found installed product - Global Location
21-12-2014 8:43:43 PM - Found installed product - ssms

21-12-2014 8:43:43 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by TomSmartBishop** [comment]
Works with VS2013
